name: build on schedule

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - run: git config --global user.name sakkke
      - run: git config --global user.email 84666033+sakkke@users.noreply.github.com
      - run: date >> content.txt
      - run: git add content.txt && git commit -m update && git push